### PR TITLE
change "audio/mp4" to "audio/x-m4a"

### PR DESCRIPTION
**Pull request by MylesBorins**
This has been changed in mime-db and is causing test failures

### CODE REVIEW

**Comment by TheAlphaNerd** [comment]
you may want to take only the test change... but this is currently broken on every version of node on every major platform we smoke test

disclaimer: I work on node core... specifically around ecosystem stability and smoketesting

**Comment by broofa** [comment]
Thanks for the heads up.

I'm inclined to say that audio/mp4 is the "more correct" mapping here.  'Looks like what happened is that nginx added the audio/x-m4a definition to their types file, which mime-db picked up and which causes some conflict with the audio/mp4 definition from Apache uses.

Rather than patch the test and types.json file, I think it makes more sense to change build.js so it prioritizes official types over experimental ones when building types.json.

Thoughts?

**Comment by TheAlphaNerd** [comment]
@broofa that sounds like a reasonable idea. I dug through the code and it looks like what is happening is that dupes are overwriting. It seems to be like this change will be non-trivial, and might have some performance implications if it is not done in the db parsing stage.

Thoughts?

**Comment by TheAlphaNerd** [comment]
ping @broofa

**Comment by broofa** [comment]
Will be closed in #156

**Pull request closed without merging**
